services:
  - type: web
    name: openapi-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --worker-class gevent --timeout 30
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: EMAIL
        value: maurizio.secco@taxdry.com
      - key: API_KEY
        value: w2l5e7ckhmqqzawtbvqw9nnkhbsskqsz
      - key: TOKEN
        value: 683630af5750ead9fd034507  # opzionale se vuoi usare un token fisso


